### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by simonsan** [ShadoySV/work-break#1]
Hey there,
I found your tool by chance while searching for pomodoro or something on crates.io.

I'm currently building https://github.com/pace-rs/pace because I felt my use case for tracking work and break times is not fulfilled by a lot of tools out there. I see that you also spend a lot of time thinking about time management techniques and I like what you did with `work-break` as it inspired me for some ideas for `pace`.

> Doing the same work should be discouraged. Working together should be applauded.

Based on that, I wanted to ask if you feel like joining the cause and help to implement `pace`. :) There is a discord link in the repository, if you want to discuss further, would be happy to see you there.

Cheers,
Simon

**Comment by ShadoySV** [comment]
Hey, @simonsan ! Thanks for reaching out. My use case working full-time is completely fulfilled with ```work-break```, so I'm not inspired to work on something else now.
